language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
before_script:
    - python -m solc.install v0.4.19
script:
    - pytest
    - flake8
notifications:
    email: false
